--------------------------------------------------------------------------------
-- File: axi_test_axion_reg.vhd
-- Description: AXI Register Interface Module
-- Generated by Axion HDL
--
-- Module: axi_test
-- Source: axi_test.json
-- Author: bugratufan
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.axion_common_pkg.all;

entity axi_test_axion_reg is
    generic (
        BASE_ADDR : std_logic_vector(31 downto 0) := x"00004000"
    );
    port (
        -- AXI4-Lite Interface
        axi_aclk    : in  std_logic;
        axi_aresetn : in  std_logic;
        
        -- AXI4-Lite typed record ports (axion_common_pkg)
        axi_m2s     : in  t_axi_lite_m2s;
        axi_s2m     : out t_axi_lite_s2m;
        
        -- Register Signals
        version : out std_logic_vector(31 downto 0);
        val : out std_logic_vector(31 downto 0)
    );
end entity axi_test_axion_reg;

architecture rtl of axi_test_axion_reg is
    
    -- AXI4-Lite Compliant State Machine
    -- Supports independent address and data channels per AXI-LITE-005
    type axi_state_type is (IDLE, WR_WAIT_ADDR, WR_WAIT_DATA, WR_DO_WRITE, WR_RESP, RD_ADDR, RD_DATA);
    signal axi_state : axi_state_type;
    
    -- Internal signals for write transaction
    signal wr_addr_reg : std_logic_vector(31 downto 0);
    signal wr_data_reg : std_logic_vector(31 downto 0);
    signal wr_strb_reg : std_logic_vector(3 downto 0);
    
    -- Internal signals for read transaction
    signal rd_addr_reg : std_logic_vector(31 downto 0);
    signal rd_data_reg : std_logic_vector(31 downto 0);
    
    -- Access control
    signal wr_access_error : std_logic;
    signal rd_access_error : std_logic;
    signal wr_addr_valid_n : std_logic;  -- Combinational write address invalid flag
    signal rd_addr_valid_n : std_logic;  -- Combinational read address invalid flag
    
    -- Write trigger signal
    signal do_reg_write : std_logic;
    
    -- Register storage
    signal version_reg : std_logic_vector(31 downto 0) := (others => '0');
    signal val_reg : std_logic_vector(31 downto 0) := (others => '0');
    
    
    -- Intermediate signals unpacked from axi_m2s / axi_s2m record ports
    signal axi_awaddr  : std_logic_vector(31 downto 0);
    signal axi_awvalid : std_logic;
    signal axi_awprot  : std_logic_vector(2 downto 0);
    signal axi_wdata   : std_logic_vector(31 downto 0);
    signal axi_wstrb   : std_logic_vector(3 downto 0);
    signal axi_wvalid  : std_logic;
    signal axi_bready  : std_logic;
    signal axi_araddr  : std_logic_vector(31 downto 0);
    signal axi_arvalid : std_logic;
    signal axi_arprot  : std_logic_vector(2 downto 0);
    signal axi_rready  : std_logic;
    signal axi_awready : std_logic;
    signal axi_wready  : std_logic;
    signal axi_bresp   : std_logic_vector(1 downto 0);
    signal axi_bvalid  : std_logic;
    signal axi_arready : std_logic;
    signal axi_rdata   : std_logic_vector(31 downto 0);
    signal axi_rresp   : std_logic_vector(1 downto 0);
    signal axi_rvalid  : std_logic;
    
begin
    
    -- Unpack AXI M2S record into intermediate signals
    axi_awaddr  <= axi_m2s.awaddr;
    axi_awvalid <= axi_m2s.awvalid;
    axi_awprot  <= axi_m2s.awprot;
    axi_wdata   <= axi_m2s.wdata;
    axi_wstrb   <= axi_m2s.wstrb;
    axi_wvalid  <= axi_m2s.wvalid;
    axi_bready  <= axi_m2s.bready;
    axi_araddr  <= axi_m2s.araddr;
    axi_arvalid <= axi_m2s.arvalid;
    axi_arprot  <= axi_m2s.arprot;
    axi_rready  <= axi_m2s.rready;
    
    -- Pack intermediate signals into AXI S2M record
    axi_s2m.awready <= axi_awready;
    axi_s2m.wready  <= axi_wready;
    axi_s2m.bresp   <= axi_bresp;
    axi_s2m.bvalid  <= axi_bvalid;
    axi_s2m.arready <= axi_arready;
    axi_s2m.rdata   <= axi_rdata;
    axi_s2m.rresp   <= axi_rresp;
    axi_s2m.rvalid  <= axi_rvalid;
    
    ---------------------------------------------------------------------------
    -- Packed Register Mapping (Subregister connections)
    ---------------------------------------------------------------------------
    
    ---------------------------------------------------------------------------
    -- AXI4-Lite Interface State Machine
    -- Full protocol compliance per ARM AMBA AXI4-Lite specification:
    --   - AXI-LITE-001: Safe reset state for all outputs
    --   - AXI-LITE-004: VALID stability until READY
    --   - AXI-LITE-005: Independent write address and data channels
    --   - AXI-LITE-007/008: Correct response timing
    --   - AXI-LITE-016/017: Delayed and early READY handling
    ---------------------------------------------------------------------------
    process(axi_aclk)
    begin
        if rising_edge(axi_aclk) then
            if axi_aresetn = '0' then
                -- AXI-LITE-001: Reset State Requirements
                axi_state <= IDLE;
                axi_awready <= '0';
                axi_wready <= '0';
                axi_bvalid <= '0';
                axi_bresp <= "00";
                axi_arready <= '0';
                axi_rvalid <= '0';
                axi_rresp <= "00";
                wr_access_error <= '0';
                rd_access_error <= '0';
                do_reg_write <= '0';
            else
                -- Default: clear one-shot signals
                do_reg_write <= '0';
                
                case axi_state is
                    ------------------------------------
                    -- IDLE: Wait for transaction start
                    ------------------------------------
                    when IDLE =>
                        -- Check for write transaction (address or data can come first)
                        -- AXI-LITE-005: Write Address and Data Independence
                        if axi_awvalid = '1' and axi_wvalid = '1' then
                            -- Both address and data arrived simultaneously
                            axi_awready <= '1';
                            axi_wready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_DO_WRITE;
                        elsif axi_awvalid = '1' then
                            -- Address first - wait for data
                            axi_awready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_WAIT_DATA;
                        elsif axi_wvalid = '1' then
                            -- Data first - wait for address
                            axi_wready <= '1';
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            axi_state <= WR_WAIT_ADDR;
                        elsif axi_arvalid = '1' then
                            -- Read transaction
                            axi_arready <= '1';
                            rd_addr_reg <= axi_araddr;
                            rd_access_error <= rd_addr_valid_n;
                            axi_state <= RD_ADDR;
                        end if;
                    
                    ------------------------------------
                    -- WR_WAIT_ADDR: Data received, waiting for address
                    -- AXI-LITE-005: Data-first ordering support
                    ------------------------------------
                    when WR_WAIT_ADDR =>
                        axi_wready <= '0';
                        if axi_awvalid = '1' then
                            axi_awready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_DO_WRITE;
                        end if;
                    
                    ------------------------------------
                    -- WR_WAIT_DATA: Address received, waiting for data
                    -- AXI-LITE-005: Address-first ordering support
                    ------------------------------------
                    when WR_WAIT_DATA =>
                        axi_awready <= '0';
                        if axi_wvalid = '1' then
                            axi_wready <= '1';
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            axi_state <= WR_DO_WRITE;
                        end if;
                    
                    ------------------------------------
                    -- WR_DO_WRITE: Perform register write
                    ------------------------------------
                    when WR_DO_WRITE =>
                        axi_awready <= '0';
                        axi_wready <= '0';
                        do_reg_write <= '1';  -- Trigger register write
                        axi_state <= WR_RESP;
                        axi_bvalid <= '1';
                        -- AXI-LITE-014: Response Code Compliance
                        if wr_access_error = '1' then
                            axi_bresp <= "10"; -- SLVERR
                        else
                            axi_bresp <= "00"; -- OKAY
                        end if;
                    
                    ------------------------------------
                    -- WR_RESP: Wait for response acknowledgment
                    -- AXI-LITE-007: Write Response Timing
                    ------------------------------------
                    when WR_RESP =>
                        -- AXI-LITE-016/017: READY handling (immediate or delayed)
                        if axi_bready = '1' then
                            axi_bvalid <= '0';
                            axi_bresp <= "00";
                            axi_state <= IDLE;
                        end if;
                    
                    ------------------------------------
                    -- RD_ADDR: Read address received
                    ------------------------------------
                    when RD_ADDR =>
                        axi_arready <= '0';
                        axi_state <= RD_DATA;
                        axi_rvalid <= '1';
                        -- AXI-LITE-014: Response Code Compliance
                        if rd_access_error = '1' then
                            axi_rresp <= "10"; -- SLVERR
                        else
                            axi_rresp <= "00"; -- OKAY
                        end if;
                    
                    ------------------------------------
                    -- RD_DATA: Output read data
                    -- AXI-LITE-008: Read Response Timing
                    -- AXI-LITE-016/017: READY handling
                    ------------------------------------
                    when RD_DATA =>
                        if axi_rready = '1' then
                            axi_rvalid <= '0';
                            axi_rresp <= "00";
                            axi_state <= IDLE;
                        end if;
                end case;
            end if;
        end if;
    end process;
    
    -- Write Address Valid Detection (combinational)
    process(axi_awaddr)
    begin
        wr_addr_valid_n <= '1';  -- Default: invalid
        if unsigned(axi_awaddr) = unsigned(BASE_ADDR) + 0 then
            wr_addr_valid_n <= '0';  -- Valid write address
        end if;
        if unsigned(axi_awaddr) = unsigned(BASE_ADDR) + 4 then
            wr_addr_valid_n <= '0';  -- Valid write address
        end if;
    end process;
    
    -- Read Address Valid Detection (combinational)
    process(axi_araddr)
    begin
        rd_addr_valid_n <= '1';  -- Default: invalid
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 0 then
            rd_addr_valid_n <= '0';  -- Valid read address
        end if;
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 4 then
            rd_addr_valid_n <= '0';  -- Valid read address
        end if;
    end process;
    
    -- Register Write Logic
    -- Write occurs when do_reg_write is asserted (WR_DO_WRITE state)
    process(axi_aclk)
    begin
        if rising_edge(axi_aclk) then
            if axi_aresetn = '0' then
                version_reg <= x"ABCDEF01";
                val_reg <= x"DEADBEEF";
            else
                if do_reg_write = '1' and wr_access_error = '0' then
                    if unsigned(wr_addr_reg) = unsigned(BASE_ADDR) + 0 then
                        -- Byte-level write strobe
                        if wr_strb_reg(0) = '1' then
                            version_reg(7 downto 0) <= wr_data_reg(7 downto 0);
                        end if;
                        if wr_strb_reg(1) = '1' then
                            version_reg(15 downto 8) <= wr_data_reg(15 downto 8);
                        end if;
                        if wr_strb_reg(2) = '1' then
                            version_reg(23 downto 16) <= wr_data_reg(23 downto 16);
                        end if;
                        if wr_strb_reg(3) = '1' then
                            version_reg(31 downto 24) <= wr_data_reg(31 downto 24);
                        end if;
                    end if;
                    if unsigned(wr_addr_reg) = unsigned(BASE_ADDR) + 4 then
                        -- Byte-level write strobe
                        if wr_strb_reg(0) = '1' then
                            val_reg(7 downto 0) <= wr_data_reg(7 downto 0);
                        end if;
                        if wr_strb_reg(1) = '1' then
                            val_reg(15 downto 8) <= wr_data_reg(15 downto 8);
                        end if;
                        if wr_strb_reg(2) = '1' then
                            val_reg(23 downto 16) <= wr_data_reg(23 downto 16);
                        end if;
                        if wr_strb_reg(3) = '1' then
                            val_reg(31 downto 24) <= wr_data_reg(31 downto 24);
                        end if;
                    end if;
                end if;
            end if;
        end if;
    end process;
    
    -- Register Read Logic
    process(rd_addr_reg, rd_access_error
        , version_reg
        , val_reg
    )
    begin
        rd_data_reg <= (others => '0');
        if rd_access_error = '0' then
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 0 then
                rd_data_reg <= version_reg;
            end if;
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 4 then
                rd_data_reg <= val_reg;
            end if;
        end if;
    end process;
    
    axi_rdata <= rd_data_reg;
    
    -- Read-Write (out port - AXI reads/writes, module reads): version
    version <= version_reg;
    -- Read-Write (out port - AXI reads/writes, module reads): val
    val <= val_reg;
end architecture rtl;
